export const MASTER_CATALOG = [
  { name: "메인 KV (가로)", ratio: "16:9", category: "현장" },
  { name: "메인 KV (세로)", ratio: "3:4", category: "현장" },
  { name: "메인 KV (정사각)", ratio: "1:1", category: "현장" },
  { name: "무대 배경", ratio: "16:9", category: "현장" },
  { name: "무대 사이드 스크린", ratio: "9:16", category: "현장" },
  { name: "포토월", ratio: "16:9", category: "현장" },
  { name: "입구 X배너", ratio: "2:3", category: "현장" },
  { name: "입구 현수막 (세로)", ratio: "1:3", category: "현장" },
  { name: "가로 현수막", ratio: "3:1", category: "현장" },
  { name: "대형 현수막", ratio: "5:1", category: "현장" },
  { name: "에어간판", ratio: "1:4", category: "현장" },
  { name: "포디움 로고 패널", ratio: "4:3", category: "현장" },
  { name: "바닥 사인", ratio: "1:1", category: "현장" },
  { name: "안내 사이니지 (세로)", ratio: "9:16", category: "현장" },
  { name: "안내 사이니지 (가로)", ratio: "16:9", category: "현장" },
  { name: "층별 안내 사인", ratio: "3:4", category: "현장" },
  { name: "화살표 방향 안내", ratio: "2:1", category: "현장" },
  { name: "LED 전광판", ratio: "6:1", category: "현장" },
  { name: "프로그램 북 표지", ratio: "3:4", category: "인쇄" },
  { name: "리플릿 표지", ratio: "3:4", category: "인쇄" },
  { name: "초대장", ratio: "5:7", category: "인쇄" },
  { name: "명찰 (가로)", ratio: "1.4:1", category: "인쇄" },
  { name: "명찰 (세로)", ratio: "1:1.4", category: "인쇄" },
  { name: "테이블 텐트카드", ratio: "2:1", category: "인쇄" },
  { name: "봉투", ratio: "16:9", category: "인쇄" },
  { name: "스티커", ratio: "1:1", category: "인쇄" },
  { name: "포스터 (A1)", ratio: "1:1.414", category: "인쇄" },
  { name: "포스터 (A2)", ratio: "1:1.414", category: "인쇄" },
  { name: "엽서", ratio: "3:2", category: "인쇄" },
  { name: "수료증 / 인증서", ratio: "1.414:1", category: "인쇄" },
  { name: "상장", ratio: "1.414:1", category: "인쇄" },
  { name: "인스타그램 피드", ratio: "1:1", category: "디지털" },
  { name: "인스타그램 스토리", ratio: "9:16", category: "디지털" },
  { name: "인스타그램 릴스 커버", ratio: "9:16", category: "디지털" },
  { name: "페이스북 이벤트 커버", ratio: "16:9", category: "디지털" },
  { name: "트위터/X 헤더", ratio: "3:1", category: "디지털" },
  { name: "유튜브 썸네일", ratio: "16:9", category: "디지털" },
  { name: "카카오톡 공유 이미지", ratio: "1.91:1", category: "디지털" },
  { name: "링크드인 배너", ratio: "4:1", category: "디지털" },
  { name: "블로그 대표 이미지", ratio: "16:9", category: "디지털" },
  { name: "이메일 헤더", ratio: "2:1", category: "디지털" },
  { name: "이메일 풋터 배너", ratio: "3:1", category: "디지털" },
  { name: "웹사이트 히어로 배너", ratio: "21:9", category: "디지털" },
  { name: "웹사이트 OG 이미지", ratio: "1.91:1", category: "디지털" },
  { name: "팝업 배너", ratio: "1:1.2", category: "디지털" },
  { name: "Zoom 가상 배경", ratio: "16:9", category: "디지털" },
  { name: "Teams 가상 배경", ratio: "16:9", category: "디지털" },
  { name: "웨비나 타이틀 슬라이드", ratio: "16:9", category: "디지털" },
  { name: "에코백 디자인", ratio: "1:1", category: "굿즈" },
  { name: "텀블러 랩", ratio: "3:1", category: "굿즈" },
  { name: "머그컵 디자인", ratio: "2:1", category: "굿즈" },
  { name: "티셔츠 전면 프린트", ratio: "1:1", category: "굿즈" },
  { name: "노트 표지", ratio: "3:4", category: "굿즈" },
  { name: "USB/카드 디자인", ratio: "1.6:1", category: "굿즈" },
  { name: "기프트 박스 라벨", ratio: "2:1", category: "굿즈" },
] as const;

export const CATEGORIES = ["전체", "현장", "인쇄", "디지털", "굿즈"] as const;

export const STYLE_CATEGORIES = [
  "다크+네온", "화이트+미니멀", "우드+내추럴", "일러스트+플랫",
  "그라데이션+모던", "모노크롬", "레트로+빈티지", "럭셔리+골드",
  "테크+디지털", "캐주얼+팝",
] as const;

export const EVENT_TYPES = [
  "세미나", "컨퍼런스", "시상식", "전시", "네트워킹", "교육", "축제",
] as const;

export const SERVICE_TIERS = [
  {
    id: "self" as const,
    name: "셀프",
    desc: "파일만 받아서 직접 처리",
    price: "가격 미정",
    features: ["AI 생성", "업스케일", "레퍼런스 검색", "PPT 생성", "ZIP 다운로드"],
  },
  {
    id: "basic" as const,
    name: "기본",
    desc: "인쇄해서 배달까지",
    price: "가격 미정",
    features: ["AI 생성", "업스케일", "레퍼런스 검색", "PPT 생성", "ZIP 다운로드", "인쇄 제작", "행사장 배달"],
  },
  {
    id: "full" as const,
    name: "풀",
    desc: "리터치부터 설치까지 올인원",
    price: "가격 미정",
    features: ["AI 생성", "업스케일", "레퍼런스 검색", "PPT 생성", "ZIP 다운로드", "인쇄 제작", "행사장 배달", "디자이너 리터치", "현장 설치/철거"],
  },
] as const;
